### ISSUE TITLE
Start looking into data/map implementation

### ISSUE THREAD

**Issue by achlong** [Hyperobjekt/crs#15]
Spec: https://docs.google.com/document/d/193DDmppsCZuD9YqzsmFd_w-ZUUNXl0axnQpXhLQQYVY/edit

Data set attached

**Comment by achlong** [comment]
[https://app.zenhub.com/files/428439456/00959006-f422-4010-bfa5-078ab8622ed2/download](https://app.zenhub.com/files/428439456/00959006-f422-4010-bfa5-078ab8622ed2/download)

**Comment by coreytegeler** [comment]
Current tech stack:
- Framework: Next.js
- Mapping: SVG w/ d3.js
